% 关联文档: docs/planning/BOC_TDMA_System_Planning.md v1.2 §6 阶段 A
% 关联上下文: AI_CONTEXT.md
% 阶段定位: P0-A 参数级自洽检查（纯 MATLAB、零硬件依赖）
% 说明: 只检查系统参数与派生参数的一致性，不生成波形，不触碰硬件。

fprintf('\n');
fprintf('============================================================\n');
fprintf('BOC-TDMA P0-A 参数级自洽检查\n');
fprintf('============================================================\n');

% 锁定基础参数
fs = 36e6;
fc = 3e6;
fsc = 15e6;
Nchip_slot = 750;
N_s = 32;

% 派生参数
Tc = 1 / fc;
Nc = fs / fc;
Nslot = Nchip_slot * Nc;
Tslot = Nslot / fs;
Nframe = N_s * Nslot;
Tframe = Nframe / fs;
bit_rate = 1 / Tframe;
process_gain_db = 10 * log10(Nchip_slot);
fs_over_fsc = fs / fsc;
fsc_over_fc = fsc / fc;
Nsc_slot = fsc * Tslot;

pass_count = 0;
warn_count = 0;
fail_count = 0;

fprintf('锁定基础参数:\n');
fprintf('  fs         = %.0f Hz\n', fs);
fprintf('  fc         = %.0f Hz\n', fc);
fprintf('  fsc        = %.0f Hz\n', fsc);
fprintf('  Nchip_slot = %d chips\n', Nchip_slot);
fprintf('  N_s        = %d slots/frame\n', N_s);

fprintf('\n检查结果:\n');
[pass_count, warn_count, fail_count] = emit_numeric_check( ...
    '码片时长 Tc', Tc, 1 / fc, 1e-18, ...
    sprintf('%.6f ns', Tc * 1e9), ...
    '333.333333 ns', ...
    '定义与锁定码速率一致。', ...
    pass_count, warn_count, fail_count);
[pass_count, warn_count, fail_count] = emit_numeric_check( ...
    '每码片采样点数 Nc', Nc, 12, 1e-12, ...
    sprintf('%.6f', Nc), ...
    '12', ...
    '为整数，可直接做码片级上采样。', ...
    pass_count, warn_count, fail_count);
[pass_count, warn_count, fail_count] = emit_numeric_check( ...
    '每时隙采样点数 Nslot', Nslot, 9000, 1e-9, ...
    sprintf('%.0f', Nslot), ...
    '9000', ...
    '满足 750 chips × 12 点/码片。', ...
    pass_count, warn_count, fail_count);
[pass_count, warn_count, fail_count] = emit_numeric_check( ...
    '单时隙时长 Tslot', Tslot, 250e-6, 1e-18, ...
    sprintf('%.6f us', Tslot * 1e6), ...
    '250.000000 us', ...
    '与系统规划中的 250 us 一致。', ...
    pass_count, warn_count, fail_count);
[pass_count, warn_count, fail_count] = emit_numeric_check( ...
    '每周期采样点数 Nframe', Nframe, 288000, 1e-6, ...
    sprintf('%.0f', Nframe), ...
    '288000', ...
    '满足 32 时隙拼接关系。', ...
    pass_count, warn_count, fail_count);
[pass_count, warn_count, fail_count] = emit_numeric_check( ...
    '单周期时长 Tframe', Tframe, 8e-3, 1e-18, ...
    sprintf('%.6f ms', Tframe * 1e3), ...
    '8.000000 ms', ...
    '与 TDMA 帧周期一致。', ...
    pass_count, warn_count, fail_count);
[pass_count, warn_count, fail_count] = emit_numeric_check( ...
    '信息速率', bit_rate, 125, 1e-12, ...
    sprintf('%.6f bps', bit_rate), ...
    '125.000000 bps', ...
    '对应每周期 1 bit。', ...
    pass_count, warn_count, fail_count);
[pass_count, warn_count, fail_count] = emit_numeric_check( ...
    '处理增益', process_gain_db, 10 * log10(750), 1e-12, ...
    sprintf('%.6f dB', process_gain_db), ...
    '28.750612 dB', ...
    '与 10log10(750) 一致。', ...
    pass_count, warn_count, fail_count);
[pass_count, warn_count, fail_count] = emit_warn_check( ...
    '子载波采样比 fs/fsc', ...
    sprintf('%.6f', fs_over_fsc), ...
    '2.400000', ...
    '预期行为，不是错误；虽然每个子载波周期对应 2.4 个采样点，但每码片恰好包含 5 个完整子载波周期、每时隙包含 3750 个完整周期，因此风险受控。', ...
    pass_count, warn_count, fail_count);
[pass_count, warn_count, fail_count] = emit_numeric_check( ...
    '每码片完整子载波周期数 fsc/fc', fsc_over_fc, 5, 1e-12, ...
    sprintf('%.6f', fsc_over_fc), ...
    '5.000000', ...
    '每码片内完整子载波周期数为整数。', ...
    pass_count, warn_count, fail_count);
[pass_count, warn_count, fail_count] = emit_numeric_check( ...
    '每时隙完整子载波周期数 fsc*Tslot', Nsc_slot, 3750, 1e-9, ...
    sprintf('%.6f', Nsc_slot), ...
    '3750.000000', ...
    '时隙边界处不发生周期累计漂移。', ...
    pass_count, warn_count, fail_count);

fprintf('\n检查摘要:\n');
fprintf('  PASS = %d\n', pass_count);
fprintf('  WARN = %d\n', warn_count);
fprintf('  FAIL = %d\n', fail_count);

if fail_count == 0
    fprintf('  结论: 允许进入后续 MATLAB 脚本开发。\n');
else
    fprintf('  结论: 暂不允许进入后续 MATLAB 脚本开发，请先修复 FAIL 项。\n');
end

fprintf('  说明: 当前仍不触碰硬件；USRP / 频谱仪验证属于 P0-B 或后续阶段。\n');
fprintf('============================================================\n\n');

function [pass_count, warn_count, fail_count] = emit_numeric_check( ...
    name, value, expected, tol, value_desc, expected_desc, note, ...
    pass_count, warn_count, fail_count)

if abs(value - expected) <= tol
    status = '√';
    pass_count = pass_count + 1;
else
    status = '×';
    fail_count = fail_count + 1;
end

fprintf('  %s %-24s 实测=%-18s 预期=%-18s %s\n', ...
    status, name, value_desc, expected_desc, note);
end

function [pass_count, warn_count, fail_count] = emit_warn_check( ...
    name, value_desc, expected_desc, note, pass_count, warn_count, fail_count)

status = '⚠';
warn_count = warn_count + 1;

fprintf('  %s %-24s 实测=%-18s 预期=%-18s %s\n', ...
    status, name, value_desc, expected_desc, note);
end
